spring:
  application:
    name: graph-plotter
  datasource:
    url: jdbc:mysql://localhost:3306/graph_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true